{% set name = "pyiron_gui" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_gui-{{ version }}.tar.gz
  sha256: eece5e6245aa2cbc4efb49b2c1e5c50755c173d7579852993fb2e0f038960f49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - ipywidgets>=8.0.6
    - pyiron_base >=0.5.35
    - pyiron_atomistics >=0.2.65
    - numpy >=1.23.4
    - pandas >=1.5.1
    - matplotlib-base >=3.7.1
    - nbconvert >=7.3.1
    - nbformat >=5.8.0

test:
  imports:
    - pyiron_gui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_gui
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Extended graphical user interface (GUI) for pyiron the integrated development environment (IDE)
  description: |
    extended graphical user interface (GUI) for pyiron the integrated development environment (IDE)
  doc_url: https://github.com/pyiron/pyiron_gui
  dev_url: https://github.com/pyiron/pyiron_gui

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
