{% set name = "pyiron_gui" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_gui-{{ version }}.tar.gz
  sha256: eece5e6245aa2cbc4efb49b2c1e5c50755c173d7579852993fb2e0f038960f49
  patches:
    - versioneer.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyiron_base >=0.5.35
    - pyiron_atomistics >=0.2.65
    - ipywidgets >=8.0.6
    - matplotlib-base >=3.7.1
    - nbconvert >=7.3.1
    - nbformat >=5.8.0
    - numpy >=1.24.2
    - pandas >=2.0.0

test:
  imports:
    - pyiron_gui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_gui
  summary: Repository for GUI plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
