{% set name = "pyiron_gui" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_gui-{{ version }}.tar.gz
  sha256: 5752f40ef288d442cd7a001e2418e34562d8f380e50a5b4a7a704bb4f20e98c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyiron_base >=0.7.7
    - pyiron_atomistics >=0.4.17
    - ipywidgets >=8.1.2
    - matplotlib-base >=3.8.3
    - nbconvert >=7.16.2
    - nbformat >=5.10.3
    - numpy >=1.26.4
    - pandas >=2.2.0

test:
  imports:
    - pyiron_gui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_gui
  summary: Repository for GUI plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
